language: elixir
elixir:
  - 1.3.4
  - 1.4.0
  - 1.4.5
otp_release:
  - 18.3
  - 19.2
sudo: false
script:
  - mix test
  - mix espec
  - mix espec spec_formatters/test_spec.exs
notifications:
  recipients:
    - anton.mishchuk@gmail.com
