language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.0-dev
otp_release:
  - 18.0
sudo: false
script:
  - mix test
  - mix espec --silent
  - mix espec --format=json --out=spec.json
  - mix espec --format=html --out=spec.html
notifications:
  recipients:
    - anton.mishchuk@gmail.com
