language: elixir
elixir:
  - 1.2.6
  - 1.3.4
  - 1.4.0
otp_release:
  - 18.3
  - 19.2
sudo: false
script:
  - mix test
  - mix espec
  - mix espec --format=json --out=spec.json
  - mix espec --format=html --out=spec.html
notifications:
  recipients:
    - anton.mishchuk@gmail.com
