language: elixir
elixir:
  - 1.2.0
  - 1.2.4
  - 1.3.0
otp_release:
  - 18.2
  - 19.0
sudo: false
script:
  - mix test
  - mix espec --silent
  - mix espec --format=json --out=spec.json
  - mix espec --format=html --out=spec.html
notifications:
  recipients:
    - anton.mishchuk@gmail.com
